### ISSUE TITLE
Jetpacks not including Elytra

### ISSUE THREAD

**Issue by RedLion666** [PssbleTrngle/CreateJetpack#101]
### What happened?

 Playing multiplayer Steampunk LPS version 21.5.
 
Issue: Both tiers of jetpack, which require an Elytra as an ingredient and show it in the items' sprites, do not visually or mechanically equip the Elytra. Pressing space while mid-air with a jetpack equipped will only activate the upwards thrust and not commence gliding or glide boosting. When activating F5 and visually inspecting my character, there is no Elytra on my model. In order to use the Elytra and jetpack at the same time, I must equip them separately. I am the only person on the server who is experiencing this issue.

### Loader

forge

### Mod Version

3.3.0

### Minecraft Version

1.19

**Comment by PssbleTrngle** [comment]
This is not a bug, but the intended functionality, the elytra in the recipe is only there as an ingredient for balancing purposes, not because it is automatically included with the jetpack. In order to use them together, you'd have to equip an elytra separately using a curios slot.
I get that it being included in the recipe causes this confusion, but on the other hand I wanted it there to balance it.
