### ISSUE TITLE
Option to put jetpack in different slots

### ISSUE THREAD

**Issue by PssbleTrngle** [PssbleTrngle/CreateJetpack#16]
### Describe the feature you have in mind.

It would be nice for mod compatiblity if the jetpack could be put into special slots like:
- Curios Back Slot?
- Galacticcraft Backpack slot?

But maybe also not the way I want to balance things

**Comment by atzelpool** [comment]
Hello, what I mentioned about the slot for the jetpack is because some mods use effects when having all the armor and it touches the armor, this is because, like some jetpack mods, they use a special slot so as not to lose the benefits just as create uses curios for glasses,
It's just a feature that occurred to me, your mod has impressed me

**Comment by PssbleTrngle** [comment]
While that does make sense, create also does not use the back slot for the copper backtank, which the jetpack is heavily based on

**Comment by PssbleTrngle** [comment]
I've added support for the curios slots, specifically the back slot.
It just has to be added using a datapack, like described in the README
