### ISSUE TITLE
Netherite jetpack does not apply Netherite backtank fire resistance

### ISSUE THREAD

**Issue by thrilliams** [PssbleTrngle/CreateJetpack#88]
### What happened?

Steps to reproduce:
- equip a Netherite jetpack while wearing a Netherite diving helmet, leggings, and either diving boots or Netherite boots
- step in some lava

Expected result: 
- no fire

Actual result:
- fire

### Loader

fabric

### Mod Version

v4.1.0

### Minecraft Version

1.20

**Comment by steve-the-player** [comment]
I have died to this multiple times. Any news on when we can expect the bugfix @PssbleTrngle?

**Comment by PssbleTrngle** [comment]
Thanks to an a bit hacky mixin into the create code, this should now be fixed. Two warning tho:
1. This does not work when the jetpack is equipped in a trinket slot, the same as it would not work with a backtank in the trinket slot
2. You probably have to re-requip it once, since the fabric version of create only updates the lava resistance once the armor items chance
